# Generated by Django 4.1.3 on 2022-11-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe', '0002_remove_item_stripe_price_id_item_currency_item_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='photo',
            field=models.ImageField(default='https://image.shutterstock.com/image-vector/available-now-label-badge-seal-260nw-700610512.jpg', upload_to='', verbose_name='Фото'),
        ),
    ]
